# Generated by Django 4.1.7 on 2023-03-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_photo_profil_author_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
